INSERT INTO ITEMS(ID, CATEGORY, "NAME", PRICE) VALUES(1, 'BOOKS', 'HOLY BOOK', 15);
INSERT INTO ITEMS(ID, ZC, CATEGORY, "NAME", PRICE) VALUES(2, 21440, 'COMPUTING', 'HP', 250);
INSERT INTO ITEMS(ID, AGE, CATEGORY, "NAME", PRICE) VALUES(3, 2, 'VEHICLES', 'OPEL', 5000);
INSERT INTO ITEMS(ID, DESCRIPTION, CATEGORY, "NAME", PRICE) VALUES(4, 'Very well price, buy it!', 'GAMES', 'PES 2016', 50.80);
INSERT INTO ITEMS(ID, STATUS, CATEGORY, "NAME", PRICE) VALUES(5, 'MINT', 'OTHERS', 'Bag', 5);